name: WHPromiseCI

on:
  push:
    branches:
      - master
      - develop
      - feature/*      
  pull_request:
    branches:
      - master
      - develop
      - feature/*
jobs:
  build:

    runs-on: macos-latest

    steps:
    - name: check
      uses: actions/checkout@v2
    - name: Bundle install
      run: bundle install --jobs 8
    - name: Build and test
      run: bundle exec fastlane test
